server:
  port: 9000

spring:
  application:
    name: apartment.parking.manager
  config:
    activate:
      on-profile: dev
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?sslmode=require&?prepareThreshold=0
    username: postgres.gipaatdvbnmahvpwphtk
    password: "!@!L1e2e34!!!"
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 3000
      idle-timeout: 30000
      max-lifetime: 240000

  jpa:
    properties:
      hibernate:
        type:
          bind: true
        format_sql: true
        #use_sql_comments: false
        # show_sql: 'true'
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
    # org.hibernate.type.descriptor.sql: trace
